jobs:
  check_commit:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: dragonwell-releng/check_commit_action@master
name: Dragonwell_8_commit_style_check
on:
  repository_dispatch:
    types: trigger-ga___check_pr.yml
